FROM alpine as builder
RUN apk update && apk add alpine-sdk clang
COPY cctools/cctools /build/
WORKDIR /build
RUN ./configure && make || true

FROM alpine

COPY --from=builder /build/misc/lipo /usr/bin/lipo
WORKDIR /app

ENTRYPOINT ["/usr/bin/lipo"]
